version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      NESTED_MODULES: ''
      API_DIRS: ''
      MANIFEST_OUT: ''
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/...'
      COMPONENTS: 'openmcp-bootstrapper'
      REPO_URL: 'https://github.com/openmcp-project/bootstrapper'
      GENERATE_DOCS_INDEX: "true"
      CHART_COMPONENTS: "[]"
