apiVersion: openmcp.cloud/v1alpha1
kind: ClusterProvider
metadata:
  name: "{{ .values.name }}"
spec:
  image: "{{ .values.image.location }}"
{{- if dig "image" "imagePullSecrets" "" .values }}
  imagePullSecrets:
{{- range $index, $value := .values.image.imagePullSecrets }}
    - name: "{{ $value }}"
{{- end }}
{{- end }}
{{- if dig "config" "" .values }}
{{ toYaml .values.config | indent 2 }}
{{- end }}
